language: python
python:
  - "3.5"
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpq-dev python3-dev
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c 'CREATE DATABASE botos_ci_db;' -U postgres
  - mv botos/botos/botos/settings/travis_settings.py \
       botos/botos/botos/settings/local_settings.py
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
